export interface IProduct 
{
        id: number,
        title: string,
        description: string,
        category: string,
        price: number,
        discountPercentage: number,
        rating: number,
        stock: number,
        tags: Array<string>,
        brand: string,
        sku: string,
        weight: number,
        dimensions: {},
        warrantyInformation: string,
        shippingInformation: string,
        availabilityStatus: string,
        reviews: [],
        returnPolicy: string,
        minimumOrderQuantity: number,
        meta: {},
        thumbnail: string,
        images: Array<string>,
}